# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08389732afcebdb15db62a80be6bfaafda6d7cd00fa212713bd74fb0436f02170e1b35162ce30ef84b02015129f30040e2853f8edc4aaee4cf860530a7a40a0

test:
  secret_key_base: 201aae7ef2c71879977ae37a1b0d409d4c6098d8b206afccc62d94eb18f25d855abe6a9279d4150fe77e3b2c2c0a4489f8ff3c08276bf400ccd8c8f350d99e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
